root: true

env:
  es2020: true
  node: true

extends:
  - 'semistandard'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:eslint-plugin-jsdoc/recommended-typescript'
  - 'prettier'

overrides:
  - files: ['bin/**/*']
    parserOptions:
      sourceType: 'module'
  - env:
      mocha: true
    files: ['test/**/*']
    rules:
      '@typescript-eslint/no-unused-vars': 'off'
      'jsdoc/require-file-overview': 'off'
  - files: ['test-d/**/*', './*.js']
    rules:
      'jsdoc/require-file-overview': 'off'

parser: '@typescript-eslint/parser'

rules:
  '@typescript-eslint/no-explicit-any': 'off'
  'no-useless-constructor': 'off'
  'lines-between-class-members': 'off'
  'no-use-before-define': 'off'
  '@typescript-eslint/ban-types':
    - 'error'
    - extendDefaults: true
      types:
        '{}': false
  'jsdoc/informative-docs': 'warn'
  'jsdoc/require-asterisk-prefix': 'warn'
  'jsdoc/require-file-overview': 'warn'
  'jsdoc/require-jsdoc':
    - 'warn'
    - contexts:
        [
          'TSAsExpression[typeAnnotation.typeName.name=const] > ObjectExpression :function',
        ]
  'jsdoc/tag-lines':
    - 'warn'
    - 'never'
    - startLines: 1

settings:
  jsdoc:
    tagNamePreference:
      file:
        replacement: 'packageDocumentation'
    structuredTags:
      defaultValue:
        name: 'text'
        type: false
        required: ['name']
      category:
        name: 'text'
        type: false
        required: ['name']
      typeParam:
        name: 'text'
        type: false
        required: ['name']
      remarks:
        name: 'text'
        type: false
